(() => {
  const CONFIGURED = window.SUPABASE_URL && !window.SUPABASE_URL.includes('YOUR-PROJECT') && window.SUPABASE_ANON_KEY && !window.SUPABASE_ANON_KEY.includes('YOUR_');
  const sb = CONFIGURED && window.supabase ? window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY) : null;
  const $ = (s, p=document) => p.querySelector(s); const $$ = (s,p=document) => [...p.querySelectorAll(s)];
  const money = n => `LKR ${Number(n||0).toLocaleString('en-LK')}`;
  const classData = [
    {name:'Grade 6', code:'G06', fee:2500, desc:'Foundations, core concepts and guided practice.'},
    {name:'Grade 7', code:'G07', fee:2500, desc:'Build strong understanding with structured theory.'},
    {name:'Grade 8', code:'G08', fee:2750, desc:'Concepts, applications and exam preparation.'},
    {name:'Grade 9', code:'G09', fee:3000, desc:'Higher-level thinking and deeper science concepts.'},
    {name:'Grade 10', code:'G10', fee:3500, desc:'O/L pathway with focused theory and practice.'},
    {name:'Grade 11', code:'G11', fee:4000, desc:'O/L theory, revision and exam-oriented preparation.'},
    {name:'Rapid Revision 2026', code:'RR26', fee:3500, desc:'Fast-track revision program for 2026 exams.'}
  ];
  const escapeHtml = s => String(s??'').replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function setupLoader(){window.addEventListener('load',()=>setTimeout(()=>$('#loader')?.classList.add('hide'),350));}
  function setupNav(){ const page=document.body.dataset.page; $$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page)); $('.nav-toggle')?.addEventListener('click',()=>$('.nav')?.classList.toggle('open')); }
  function setupReveal(){ const els=$$('.reveal'); if(!els.length)return; const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08}); els.forEach(e=>io.observe(e)); }
  function renderClasses(){ const grid=$('#class-grid'); if(!grid)return; grid.innerHTML=classData.slice(0,6).map((c,i)=>`<article class="class-card reveal delay-${Math.min(i,3)}"><div class="class-top"><span>${c.code}</span><span>${String(i+6).padStart(2,'0')}</span></div><h3>${c.name}</h3><p>${c.desc}</p><div class="class-meta"><span>${money(c.fee)} / month</span><button class="pay-link pay-btn" data-class="${escapeHtml(c.name)}">Payment →</button></div></article>`).join(''); $$('.pay-btn').forEach(b=>b.addEventListener('click',()=>openPayment(b.dataset.class))); setupReveal(); }
  function openPayment(name){ const modal=$('#payment-modal'); if(!modal){location.href=`payment.html?class=${encodeURIComponent(name)}`;return;} modal.classList.add('show'); const select=$('#payment-class'); if(select){select.innerHTML=classData.map(c=>`<option value="${escapeHtml(c.name)}">${escapeHtml(c.name)}</option>`).join(''); select.value=name; updateAmount(name); select.onchange=()=>updateAmount(select.value); } }
  function updateAmount(name){ const c=classData.find(x=>x.name===name); if($('#payment-amount'))$('#payment-amount').textContent=money(c?.fee||0); }
  function setupPayment(){ const form=$('#payment-form')||$('#payment-form-standalone'); if(!form)return; const q=new URLSearchParams(location.search); if(q.get('class')){const sel=form.querySelector('[name="class_name"]'); if(sel){sel.value=q.get('class'); updateAmount(sel.value);}} form.querySelector('[name="class_name"]')?.addEventListener('change',e=>updateAmount(e.target.value)); $('.modal-close')?.addEventListener('click',()=>$('#payment-modal')?.classList.remove('show')); $('#payment-modal')?.addEventListener('click',e=>{if(e.target.id==='payment-modal')e.target.classList.remove('show')}); form.addEventListener('submit', async e=>{e.preventDefault(); const status=$('#payment-status'); status.textContent='Submitting…'; status.className='form-status'; const fd=new FormData(form); const slip=fd.get('slip'); if(!sb){status.textContent='Supabase is not configured yet. Add your project URL and publishable/anon key in js/config.js.';status.classList.add('error');return;} try{const studentId=String(fd.get('student_id')).trim().toUpperCase(); const path=`${studentId}/${Date.now()}-${slip.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`; const upload=await sb.storage.from('payment-slips').upload(path,slip,{upsert:false}); if(upload.error)throw upload.error; const {error}=await sb.from('payments').insert({student_name:fd.get('student_name'),student_id:studentId,class_name:fd.get('class_name'),month:fd.get('month'),amount:classData.find(c=>c.name===fd.get('class_name'))?.fee||0,slip_path:path,status:'pending'}); if(error)throw error; status.textContent='Payment submitted successfully. The teacher will verify it.';status.classList.add('success');form.reset(); updateAmount('Grade 6');}catch(err){console.error(err);status.textContent=err.message||'Could not submit payment.';status.classList.add('error');}}); }
  async function routeAuthenticatedUser(){
    if(!sb)return;
    const {data:{session}}=await sb.auth.getSession();
    if(!session){location.replace('login.html');return;}
    const {data:profile,error}=await sb.from('students').select('role,student_id').eq('user_id',session.user.id).maybeSingle();
    if(error){console.error('Role lookup failed:',error);return;}
    const role=String(profile?.role||'student').trim().toLowerCase();
    const studentId=String(profile?.student_id||'').trim().toLowerCase();
    if(role==='admin' || studentId==='admin') location.replace('admin.html');
    else location.replace('student.html');
  }
  async function login(){ const form=$('#login-form'); if(!form)return; if(!sb){$('#login-status').textContent='Supabase is not configured yet. Open README.md and complete the setup.';return;} form.addEventListener('submit',async e=>{e.preventDefault();const status=$('#login-status');status.textContent='Checking access…';status.className='form-status';const id=$('#student-id').value.trim().toUpperCase();const password=$('#student-password').value;try{const {error}=await sb.auth.signInWithPassword({email:`${id.toLowerCase()}@students.scienceclass.app`,password});if(error)throw error;await routeAuthenticatedUser();}catch(err){console.error(err);status.textContent='Invalid Student ID or password. Please contact the teacher if you need help.';status.classList.add('error');}}); }
  async function studentDashboard(){ if(!$('#dashboard-content'))return; if(!sb){$('#student-loading').textContent='Supabase is not configured. See README.md.';return;} const {data:{session}}=await sb.auth.getSession(); if(!session){location.href='login.html';return;} const {data:profile,error}=await sb.from('students').select('*').eq('user_id',session.user.id).single(); if(error||!profile){$('#student-loading').textContent='Your student profile has not been activated yet. Please contact the teacher.';return;} if(String(profile.role||'').trim().toLowerCase()==='admin' || String(profile.student_id||'').trim().toLowerCase()==='admin'){location.replace('admin.html');return;} $('#student-loading').hidden=true; $('#dashboard-content').hidden=false; $('#student-id-display').textContent=profile.student_id; $('#student-name').textContent=profile.full_name.split(' ')[0]; $('#id-badge').textContent=profile.student_id; const {data:access}=await sb.from('student_access').select('class_name').eq('student_id',profile.student_id); const classes=(access||[]).map(a=>a.class_name); $('#access-grid').innerHTML=classes.map(c=>`<div class="access-card"><span>ACCESS</span><strong>${escapeHtml(c)}</strong><a href="#" data-class="${escapeHtml(c)}" class="dash-resource-link">Open resources →</a></div>`).join('')||'<div class="empty-state">No class access assigned yet.</div>'; const {data:resources}=await sb.from('resources').select('*').in('class_name',classes).order('created_at',{ascending:false}); renderResources(resources||[]); const {data:zooms}=await sb.from('zoom_details').select('*').in('class_name',classes).order('created_at',{ascending:false}); renderZoom(zooms||[]); const {data:payments}=await sb.from('payments').select('class_name,month,amount,status,created_at').eq('student_id',profile.student_id).order('created_at',{ascending:false}); renderPayments(payments||[]); }
  function resourceRow(r){return `<a class="resource-row" href="${escapeHtml(r.url||'#')}" target="_blank" rel="noopener"><div class="resource-icon">${r.type==='recording'?'▶':'↗'}</div><div><strong>${escapeHtml(r.title)}</strong><span>${escapeHtml(r.class_name)} · ${escapeHtml(r.description||'Open resource')}</span></div><b>↗</b></a>`}
  function renderResources(rs){const rec=rs.filter(r=>r.type==='recording'),mat=rs.filter(r=>r.type!=='recording'); $('#recordings-list').innerHTML=rec.map(resourceRow).join('')||'<div class="empty-state">No recordings available yet.</div>'; $('#materials-list').innerHTML=mat.map(resourceRow).join('')||'<div class="empty-state">No study materials available yet.</div>'; $('#latest-resources').innerHTML=rs.slice(0,5).map(resourceRow).join('')||'<div class="empty-state">No resources available yet.</div>'; }
  function renderZoom(zs){$('#zoom-box').innerHTML=zs.map(z=>`<div class="zoom-detail"><div><span class="eyebrow">${escapeHtml(z.class_name)}</span><h2>${escapeHtml(z.title||'Zoom Class')}</h2></div><div class="zoom-row"><span>Meeting ID</span><b>${escapeHtml(z.meeting_id)}</b></div><div class="zoom-row"><span>Password</span><b>${escapeHtml(z.password)}</b></div><a class="btn btn-primary" href="${escapeHtml(z.join_url)}" target="_blank" rel="noopener">Join Zoom ↗</a></div>`).join('')||'<div class="empty-state">No Zoom details available yet.</div>';}
  function renderPayments(ps){$('#payments-list').innerHTML=ps.map(p=>`<div class="payment-row"><div><strong>${escapeHtml(p.class_name)}</strong><span>${escapeHtml(p.month)}</span></div><b>${money(p.amount)}</b><span class="status-pill ${escapeHtml(p.status)}">${escapeHtml(p.status)}</span></div>`).join('')||'<div class="empty-state">No payments recorded yet.</div>';}
  function dashboardTabs(){ $$('.dash-tab').forEach(t=>t.addEventListener('click',()=>{$$('.dash-tab').forEach(x=>x.classList.remove('active'));$$('.dash-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(`#tab-${t.dataset.tab}`)?.classList.add('active')})); $('#logout-btn')?.addEventListener('click',async()=>{if(sb)await sb.auth.signOut();location.href='login.html'}); }
  async function admin(){if(!$('#admin-students'))return;if(!sb){$('#admin-students').textContent='Supabase not configured.';return;}const {data:{session}}=await sb.auth.getSession();if(!session){location.href='login.html';return;}const {data:me}=await sb.from('students').select('role,student_id').eq('user_id',session.user.id).single();if(!me || (String(me.role||'').trim().toLowerCase()!=='admin' && String(me.student_id||'').trim().toLowerCase()!=='admin')){document.querySelector('.admin-wrap').innerHTML='<div class="empty-state">Access denied.</div>';return;}const {data:students}=await sb.from('students').select('student_id,full_name,role,created_at').order('created_at',{ascending:false});const {data:payments}=await sb.from('payments').select('student_name,student_id,class_name,month,amount,status,created_at').order('created_at',{ascending:false}).limit(30);$('#admin-students').innerHTML=`<table><tr><th>ID</th><th>Name</th><th>Role</th></tr>${(students||[]).map(s=>`<tr><td>${escapeHtml(s.student_id)}</td><td>${escapeHtml(s.full_name)}</td><td>${escapeHtml(s.role)}</td></tr>`).join('')}</table>`;$('#admin-payments').innerHTML=`<table><tr><th>Student</th><th>Class</th><th>Month</th><th>Amount</th><th>Status</th></tr>${(payments||[]).map(p=>`<tr><td>${escapeHtml(p.student_id)}</td><td>${escapeHtml(p.class_name)}</td><td>${escapeHtml(p.month)}</td><td>${money(p.amount)}</td><td>${escapeHtml(p.status)}</td></tr>`).join('')}</table>`;$('#logout-btn')?.addEventListener('click',async()=>{await sb.auth.signOut();location.href='login.html'});}
  function contact(){const f=$('#contact-form');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(f);const msg=`Hi Teacher,\n\nName: ${fd.get('name')}\nStudent ID: ${fd.get('student_id')||'N/A'}\n\n${fd.get('message')}`;window.open(`https://wa.me/${window.WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`,'_blank');$('#contact-status').textContent='Opening WhatsApp…';});}
  setupLoader();setupNav();setupReveal();renderClasses();setupPayment();login();studentDashboard();dashboardTabs();admin();contact();
})();